spring.application.name=sendgrid

# --- CONFIGURAÇÃO SENDGRID ---
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587

spring.mail.username=apikey

# --- IMPORTAÇÃO SEGURA ---
# Tenta ler a senha do arquivo 'secrets.properties'. 
spring.config.import=optional:classpath:secrets.properties

# Propriedades de Segurança 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

